### PR TITLE
Caching for limit order fees

### PR DESCRIPTION
**Pull request by njannink**

### CODE REVIEW

**Comment by njannink** [comment]
Added Redis caching for limit-order fees to speed up performance of placing limit order repeatedly by the same client for the same asset-pairs

**Review by polonzer — COMMENTED** [review]
I think it would be better to use in-memory cache for better latency (like what we use for assets). What do you think?

**Comment by polonzer** [comment]
https://lykkex.atlassian.net/browse/LWDEV-7547

**Comment by njannink** [comment]
in memory cache will be less effective since there are 2+ HFT instances running and the clientid is part of the fee.

**Comment by njannink** [comment]
Reverted the Redis caching part, because FeeCalculator already supports in-memory caching. Remaining part is refactoring the fee logic from the MatchingEngineAdaptor to a seperate class

**Review by polonzer — APPROVED** [review]

**Pull request merged**
